// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(grunt) {
    grunt.initConfig({
      requirejs: {
        compile: {
          options: {
            baseUrl: "src",
            mainConfigFile: 'src/main.js',
            name: "main",
            out: 'src/app.min.js',
            useStrict: false,
            wrap: false,
            inlineText: true,
            stubModules: ['text'],
            optimize: "uglify2",
            optimizeAllPluginResources: true,
            findNestedDependencies: true,
            paths: {
              'text': '../assets/lib/requirejs-text/text'
            }
          }
        }
      }
    });
    grunt.loadNpmTasks('grunt-contrib-requirejs');
    return grunt.registerTask('default', 'requirejs');
  };

}).call(this);
